### ISSUE TITLE
If two person enter the chambers and none leave, they'll be stuck in there forever

### ISSUE THREAD

**Issue by acabaca24** [4E756E6F/Access_Control#2]
If two person enter the chambers and none leave, they'll be stuck in there forever

You must add a loop until someone leaves

**Comment by acabaca24** [comment]
https://github.com/4E756E6F/Access_Control/blob/4d4910fd70ce371b05df22b2d6bd572c65400698/access_controller/access_controller.ino#L133

**Comment by 4E756E6F** [comment]
DONE!!
